my:
  greeting: Hello World from config server
  list:
       values: One, Two, Three, Four
db:
   connection: "connectionString-string-from-config-server"
   host: 127.0.0.1
   port: 1200

management.endpoints.web.exposure.include: "*"