my:
  greeting: Hello World from Microservice Dev Specific config file.
  list:
       values: One, Two, Three, Four
db:
   connection: "Microservice Dev Specific connectionString-string-from-config-server on 17th Jan, 2024 \n"
   host: 127.0.0.2
   port: 1201

management.endpoints.web.exposure.include: "*"