my:
  greeting: Hello World from Microservice Specific config file now modified.
  list:
       values: One, Two, Three, Four
db:
   connection: "Microservice Specific connectionString-string-from-config-server"
   host: 127.0.0.2
   port: 1201

management.endpoints.web.exposure.include: "*"