my:
  greeting: Hello World from Microservice Development Specific config file from inside prod directory.
  list:
       values: One, Two, Three, Four
db:
   connection: "Microservice Development Specific connectionString-string-from-config-server on 17th Jan, 2024 from inside prod directory"
   host: 127.0.0.2
   port: 1209

management.endpoints.web.exposure.include: "*"