my:
  greeting: Hello World from Microservice SIT Specific config file from inside sit directory.
  list:
       values: One, Two, Three, Four
db:
   connection: "Microservice SIT Specific connectionString-string-from-config-server on 17th Jan, 2024, from inside sit directory"
   host: 127.0.0.2
   port: 1209

management.endpoints.web.exposure.include: "*"